language: node_js
node_js:
  - '10.16.0'

script:
  - npm run lint
  - npm test
  - npm run build

jobs:
  include:
    - stage: 'npm publish'
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
